version: '3.1'

services:
  web:
    image: magento/magento-cloud-docker-nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    image: magento/magento-cloud-docker-php:7.4-fpm
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
